# Generated by Django 4.1.5 on 2023-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('number_of_vacancies', models.IntegerField(verbose_name='Количество вакансий')),
                ('average_salary_by_profession', models.FloatField(verbose_name='Средняя зарплата по профессии')),
                ('number_of_vacancies_by_profession', models.IntegerField(verbose_name='Количество вакансий по профессии')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
    ]
