# Generated by Django 4.1.5 on 2023-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_profession_alter_yearstatistics_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySalaryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Средняя зарплата по городу',
                'verbose_name_plural': 'Средняя зарплата по городам',
            },
        ),
        migrations.CreateModel(
            name='CityShareStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('share', models.FloatField(verbose_name='Часть')),
            ],
            options={
                'verbose_name': 'Часть вакансий по городу',
                'verbose_name_plural': 'Часть вакансий по городам',
            },
        ),
    ]
